// src/components/common/select-date.tsx
import React, {useEffect, useState} from 'react';
import ReactDatePicker from 'react-datepicker';
import { ko } from 'date-fns/locale';

interface Props {
  date?: any[];
  format?: 'yyyy-MM-dd' | 'yyyy-MM-dd HH:mm';
  isAll?: boolean;
  timer?: boolean;
  onSetStartDate: (val: {date: string | null}) => void;
}

export default function SelectDate({date = [new Date().toISOString().slice(0, 10)], format = 'yyyy-MM-dd', isAll = true, onSetStartDate}: Props) {
  const [allChecked, setAllChecked] = useState(isAll);
  const [startDate, setStartDate] = useState<Date | null>(!isAll && date[0] ? new Date(date[0]) : null);
  const placeholder = format === 'yyyy-MM-dd' ? '날짜 선택' : '날짜 및 시간 선택';

  const handleToggleAll = () => {
    const newAll = !allChecked;
    setAllChecked(newAll);
    if (newAll) {
      setStartDate(null);
      onSetStartDate({date: null});
    } else {
      const now = new Date();
      setStartDate(now);
      onSetStartDate({
        date: format === 'yyyy-MM-dd' ? now.toISOString().slice(0, 10) : now.toISOString().slice(0, 16).replace('T', ' ')
      });
    }
  };

  useEffect(() => {
    if (startDate && !allChecked) {
      onSetStartDate({
        date: format === 'yyyy-MM-dd' ? startDate.toISOString().slice(0, 10) : startDate.toISOString().slice(0, 16).replace('T', ' ')
      });
    }
  }, [startDate]);

  return (
    <div style={{display: 'flex', alignItems: 'center'}}>
      <div className="all-wrap">
        {isAll && (
          <label>
            <input type="checkbox" checked={allChecked} onChange={handleToggleAll} /> 전체
          </label>
        )}
      </div>
      {!allChecked && (
        <div className="picker-wrap" style={{paddingRight: 5}}>
          <ReactDatePicker locale={ko} selected={startDate} onChange={date => setStartDate(date)} dateFormat={format === 'yyyy-MM-dd' ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm'} placeholderText={placeholder} showTimeSelect={format !== 'yyyy-MM-dd'} timeIntervals={30} timeCaption="시간" disabled={allChecked} className="input" />
        </div>
      )}
    </div>
  );
}

// src/components/SelectDate.vue
<template>
  <div class="select-date">
    <div class="term-wrap">
      <label v-show="isAll">
        <input type="checkbox" v-model="data.clickChecked" @change="toggleDatePicker" /> 전체
      </label>
    </div>
    <div class="picker-wrap" v-show="!data.clickChecked">
      <VueDatePicker
        v-model="props.date[0]"
        :locale="ko"
        :format="props.format"
        :name="props.name[0]"
        class="input"
        :placeholder="placeholderText"
        :disabled="data.clickChecked"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, watch } from 'vue';
import VueDatePicker from '@vuepic/vue-datepicker';
import { ko } from 'date-fns/locale';
import '@vuepic/vue-datepicker/dist/main.css';
import dateUtil from '@src/utils/dateUtil';

const emit = defineEmits(['set-start-date']);

const props = defineProps({
  name: { type: Array, required: true },
  date: { type: Array, required: false, default: () => [dateUtil.format(new Date(), 'yyyy-MM-dd')] },
  format: { type: String, required: false, default: 'yyyy-MM-dd' },
  isAll: { type: Boolean, required: false, default: true },
  timer: { type: Boolean, required: false, default: false },
});

const data = reactive({
  clickChecked: props.isAll,
});

const toggleDatePicker = () => {
  data.clickChecked = !data.clickChecked;
  if (data.clickChecked) {
    props.date[0] = '';
  } else {
    props.date[0] = dateUtil.format(new Date(), props.format);
  }
  emit('set-start-date', { date: props.date[0] });
};

const placeholderText = props.format === 'yyyy-MM-dd' ? '날짜 선택' : '날짜 및 시간 선택';

watch(() => props.date[0], (newDate) => {
  emit('set-start-date', { date: newDate });
});
</script>

<style scoped>
.select-date {display:flex; flex-direction: row;}
.select-date .term-wrap {flex: 1; }
.select-date .picker-wrap {flex: 9; }
</style>
