// src/components/CommonCodeRadio.vue
<template>
  <div class="common-code-radio">
    <label>
      <input
        type="radio"
        :value="''"
        v-model="data.value"
        @change="change"
      />
      {{ props.default }}
    </label>
    <label v-for="(o, idx) in auth.codeList[props.cd]" :key="idx">
      <input
        type="radio"
        :value="o.codeValue"
        v-model="data.value"
        @change="change"
      />
      {{ o.codeName }}
    </label>
  </div>
</template>

<script setup lang="ts">
import {onMounted, reactive} from 'vue';
import {useAuthStore} from '@src/store/authStore';

const auth = useAuthStore();
const emit = defineEmits(['set-data']);

const props = defineProps({
  cd: {type: String, required: true},
  model: {type: String, required: true},
  default: {type: String, default: '전체'},
});

const data = reactive({
  value: props.model,
});

const change = () => {
  emit('set-data', data.value);
};

onMounted(() => {});
</script>

<style scoped>
.common-code-radio {padding: 7px 0 4px 0;}
</style>

// src/components/common/common-code-radio.tsx
import React, {useEffect, useState} from 'react';
import useSettingStore from '@/store/use-setting-store';

interface Props {
  cd: string;
  model: string;
  defaultText?: string;
  onSetData: (value: string) => void;
}

export default function CommonCodeRadio({cd, model, defaultText = '전체', onSetData}: Props) {
  const setting = useSettingStore();
  const [value, setValue] = useState<string>(model);

  useEffect(() => {
    setValue(model); // 외부에서 model이 바뀔 경우 동기화
  }, [model]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedValue = e.target.value;
    setValue(selectedValue);
    onSetData(selectedValue);
  };

  const codeList = setting.codeList[cd] || [];

  return (
    <div className="common-code-radio" style={{padding: '7px 0 4px 0'}}>
      <label>
        <input type="radio" value="" checked={value === ''} onChange={handleChange} />
        {defaultText}
      </label>
      {codeList.map((o: any, idx: number) => (
        <label key={idx}>
          <input type="radio" value={o.codeValue} checked={value === o.codeValue} onChange={handleChange} />
          {o.codeName}
        </label>
      ))}
    </div>
  );
}
